### ISSUE TITLE
B站推送报错

### ISSUE THREAD

**Issue by 1140215216** [HeadmasterTan/zhi-plugin#14]
[YzBot][07:15:59.279][ERRO] Error: ENOENT: no such file or directory, open './data/PushNews/PushBilibiliDynamic.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at savePushJson (file:///Yunzai-Bot/plugins/zhi-plugin/apps/bilibiliPush.js:885:6)
    at initBiliPushJson (file:///Yunzai-Bot/plugins/zhi-plugin/apps/bilibiliPush.js:50:5)
    at file:///Yunzai-Bot/plugins/zhi-plugin/apps/bilibiliPush.js:77:1
    at <anonymous> (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './data/PushNews/PushBilibiliDynamic.json'
}
[YzBot][07:15:59.281][ERRO] Error: ENOENT: no such file or directory, open './data/PushNews/BilibiliPushConfig.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at saveConfigJson (file:///Yunzai-Bot/plugins/zhi-plugin/apps/bilibiliPush.js:891:6)
    at initBiliPushJson (file:///Yunzai-Bot/plugins/zhi-plugin/apps/bilibiliPush.js:73:5)
    at file:///Yunzai-Bot/plugins/zhi-plugin/apps/bilibiliPush.js:77:1
    at <anonymous> (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './data/PushNews/BilibiliPushConfig.json'
}
版本v3

**Comment by Asura648** [comment]
雀食,启动机器人的时候我也会弹这个错误出来

**Comment by HeadmasterTan** [comment]
修复啦🥰
